import { w95fa } from "@/lib/fonts";
import RootProviders from "@/providers/providers";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${w95fa.variable} ${w95fa.className} antialiased`}>
        <RootProviders>{children}</RootProviders>
      </body>
    </html>
  );
}
